### ISSUE TITLE
Would it make sense to include a little more dependencies to build tars and use "curl"

### ISSUE THREAD

**Issue by abrauner** [heroku/heroku-maven-plugin#11]
Would it make sense to remove some of the own implemenations and use common available implementations like Apache commons-compress or Apache HttpClient?

**Comment by jkutner** [comment]
Yes, initially I was trying to limit the dependencies for a use case that is no longer valid. I was also trying to support Java 6 locally, but that has been dropped. Now I can move towards using common libraries.

**Comment by abrauner** [comment]
Sounds great. Let me know if you like support on this topic than I would prepare a pull-request we can discuss.

**Comment by jkutner** [comment]
Switched to org.apache.httpcomponents:httpclient. I've had trouble with commons-compress because it can't seem to generate the Tarball exactly how I need it. So I'll probably stick with the manual packaging and compression.
