### ISSUE TITLE
No plugin found for prefix 'heroku'

### ISSUE THREAD

**Issue by guy1699** [heroku/heroku-maven-plugin#121]
Hello
I add to pom file 
```
 <plugin>
        <groupId>com.heroku.sdk</groupId>
        <artifactId>heroku-maven-plugin</artifactId>
        <version>3.0.4</version>
        <configuration>
        </configuration>
      </plugin>
```
then maven fail to import the plugin.
I add a dependency:
```
 <dependency>
      <groupId>com.heroku.sdk</groupId>
      <artifactId>heroku-maven-plugin</artifactId>
      <version>3.0.4</version>
    </dependency>
```
Now `mvn clean install` BUILD SUCCESSFULLY

But running `mvn heroku:deploy -Dheroku.appName=my-app-name`
return an ERROR:
_No plugin found for prefix 'heroku' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/gassaf/.m2/repository)_

**Comment by Malax** [comment]
Hey @guy1699, sorry for the long delay on this issue! Is it still relevant?

Can you explain what you mean by "then maven fail to import the plugin"? Do you have an error message or similar that might have a hint what is going on?

**Comment by Malax** [comment]
I'm closing this for now, feel absolutely free to re-open this later!
