### ISSUE TITLE
Doesn't seem to work with jetty-runner 

### ISSUE THREAD

**Issue by rajaraodv** [heroku/heroku-maven-plugin#18]
I am trying to use jetty-runner instead of webapp-runner. Part of the pom file looks like below. Notice that, I am also explicitly using `java $JAVA_OPTS -jar target/dependency/jetty-runner.jar --port $PORT
							target/*.war`  but still it seem to only use webapp-runner.

		<plugin>
				<groupId>com.heroku.sdk</groupId>
				<artifactId>heroku-maven-plugin</artifactId>
				<version>0.3.4</version>
				<configuration>
					<appName>aqueous-plains-2661</appName>
					<processTypes>
						<web>
							java $JAVA_OPTS -jar target/dependency/jetty-runner.jar --port $PORT
							target/*.war
						</web>
					</processTypes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.3</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>org.mortbay.jetty</groupId>
									<artifactId>jetty-runner</artifactId>
									<version>7.5.4.v20111024</version>
									<destFileName>jetty-runner.jar</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by jkutner** [comment]
When using a custom process type (or `Procfile`) you need to deploy with `mvn heroku:deploy` and not `heroku:deploy-war`. The latter is only for webapp-runner. Otherwise it looks like you have the config right. (but i do recommend upgrading to jetty-runner 9.2.7.v20150116).

Does that work? Are you getting an error?

**Comment by rajaraodv** [comment]
My POM generates a war file, so I'm not sure if I can use `mvn heroku:deploy`. So currently I am just using described here (instead of the maven plugin): https://devcenter.heroku.com/articles/deploy-a-java-web-application-that-launches-with-jetty-runner

BTW, here is the hello world app I am trying to run: https://github.com/forcedotcom/aura - this is not the aura framework itself but just a sample hello world app based on the framework.

**Comment by jkutner** [comment]
You can run `mvn heroku:deploy` regardless of the packaging. It will grab whatever is in the target dir. Have you tried it?

**Comment by rajaraodv** [comment]
Tried it and I got this exception:
```
INFO] ---> Packaging application...
[INFO]      - app: secure-beach-2025
[INFO]      - including: ./target/
[INFO]      - installing: OpenJDK 1.7
[INFO] ---> Creating slug...
[INFO]      - file: ./target/heroku/slug.tgz
[INFO]      - size: 254MB
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2015-06-25T13:53:48-07:00
[INFO] Final Memory: 23M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.heroku.sdk:heroku-maven-plugin:0.3.4:deploy (default-cli) on project helloworld2: Failed to deploy application: There was an exception invoking the remote service: HTTP(422): Server returned HTTP response code: 422 for URL: https://api.heroku.com/apps/secure-beach-2025/slugs -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```


Also, not sure why it's not picking up the ${heroku.appName} even though I have heroku.properties file that has the value. 

BTW, does specifying appName like this work well with heroku button?

**Comment by jkutner** [comment]
Looks like your heap size is too small. Try setting `MAVEN_OPTS="-Xmx1024m -Xms512m"` locally.

The Maven plugin does not work with the Heroku Button because the button requires Git deployment. But you can still mix Git deployment with Maven deployment.

It looks like appName is picked up:

> [INFO]      - app: secure-beach-2025

Is that not correct?

**Comment by jkutner** [comment]
Also, please upgrade to version 0.4.3. You may not need to increase your local heap size with the latest version (because it off-loads some of the work to the Heroku server).

**Comment by jkutner** [comment]
This should be fixed in the latest version. Please let us know if it's still not working.
