### ISSUE TITLE
Symlinks are imported into slug as files, not symlinks

### ISSUE THREAD

**Issue by tobias-** [heroku/heroku-maven-plugin#22]
When adding files with e.g.
```
		<groupId>com.heroku.sdk</groupId>
		<artifactId>heroku-maven-plugin</artifactId>
		<configuration>
		    <includes>
			<include>target/lib</include>
```
all symlinks will be turned into files and each symlink will take as much space in the slug as the ~original~ linked file. The flaw becomes most apparent when including pre-built binaries with libraries in the slug where each ".so"-library has 2-3 version symlinks.

This means that every symlink can (as in my case) take about 1MB each instead of 20 bytes, growing the slug very quickly.

**Comment by jkutner** [comment]
Released in [0.5.7](http://repo1.maven.org/maven2/com/heroku/sdk/heroku-deploy/0.5.7/)
