### ISSUE TITLE
Set API key programmatically.

### ISSUE THREAD

**Issue by rosogon** [heroku/heroku-maven-plugin#24]
Hi,

We are working in a project of a library that deploys artifacts to Heroku (for the moment). We found this project the best to deploy a war, but it only works with one account. 

For our purposes, we would need to inject the apikey to the Deployer class. Given the hierarchy of classes, the easiest way I've found is to add a public method to set the apikey in Deployer and a class extending DeployWar that accepts an apikey in the constructor:
* https://github.com/rosogon/heroku-maven-plugin/commit/5e125aeff787b31b6f80dfc111094f9ddd3e577f
* https://github.com/rosogon/heroku-java-client/blob/3bf66f38f121863e197475ccf35fa60445c51120/src/main/java/seaclouds/paas/adapter/heroku_deploy/XDeployWar.java

Do you think you can incorporate this feature? I can work on improving the previous code.

Thanks,
Román

**Comment by jkutner** [comment]
Yes, this looks fine. If you submit a PR, please also use `setEncodedApiKey` here: 
https://github.com/rosogon/heroku-maven-plugin/blob/5e125aeff787b31b6f80dfc111094f9ddd3e577f/heroku-deploy/src/main/java/com/heroku/sdk/deploy/Deployer.java#L210

I'd also be willing to merge your `XDeployWar` subclass into `DeployWar`, or maybe adding apiKey as an optional cstr arg to Deployer. What do you think about that?

**Comment by jkutner** [comment]
released in [0.5.7](http://repo1.maven.org/maven2/com/heroku/sdk/heroku-deploy/0.5.7/)
