### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by math-th** [heroku/heroku-maven-plugin#27]
Hello,

It could be great to have a console log while uploading the file to Heroku.
After this step : " -----> Uploading build..." it could be something like a println every 10%...
Because when you have a ~100MB build, it's hard to know when it will be done.

Excuse my poor english, thank you.

**Comment by jkutner** [comment]
The capability for this is actually built into the plugin in [App.java](https://github.com/heroku/heroku-maven-plugin/blob/master/heroku-deploy/src/main/java/com/heroku/sdk/deploy/App.java#L39). But it only logs on debug. 

Logging every percent was too verbose, but I think we can add something to log every 10% or so.

**Comment by math-th** [comment]
Ok thanks I didn't see it because I wasn't in debug. You're right, every percent is too verbose,but every 10% would be great, even if we add to enable it with a property or a option.

**Comment by talbright** [comment]
I passed the `-X` flag to `mvn` and there was no progress output. What's the correct way to get it to display?

`mvn -X clean package heroku:deploy`

**Comment by jkutner** [comment]
@talbright it's [disabled by default](https://github.com/heroku/heroku-maven-plugin/blob/master/heroku-deploy/src/main/java/com/heroku/sdk/deploy/App.java#L44) so even `-X` won't show it.

**Comment by talbright** [comment]
I see....so what are my options? I have a pretty large slug, and the upload has been hanging on me a lot lately. Any way for me to enable it?

**Comment by talbright** [comment]
```[INFO] -----> Uploading build...
[INFO]        - success
[INFO] -----> Deploying...
[INFO] remote:
[INFO] remote: -----> heroku-maven-plugin app detected
[INFO] remote: -----> Installing OpenJDK 1.8... done
[INFO] remote: -----> Discovering process types
[INFO] remote:        Procfile declares types -> web
[INFO] remote:
[INFO] remote: -----> Compressing...
[INFO] remote:        Done: 434.7M
[INFO] remote: -----> Launching...
[INFO] remote:  !     Warning: Your slug size exceeds our soft limit (434 MB) which may affect boot time.
[INFO] remote:        Released v20
[INFO] remote:        https://xxxx.herokuapp.com/ deployed to Heroku
[INFO] remote:
[INFO] -----> Done
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42:50 min
[INFO] Finished at: 2017-07-26T14:53:19-04:00
[INFO] Final Memory: 48M/547M
[INFO] ------------------------------------------------------------------------```

**Comment by jkutner** [comment]
@talbright i can expose the flag through a Maven config option. I'll try to put that together and cut a release this week.

**Comment by talbright** [comment]
excellant!

**Comment by jkutner** [comment]
@talbright this is available in 1.2.0. Run `mvn heroku:deploy -Dheroku.logProgress=true`

**Comment by talbright** [comment]
I don't think you ran the maven deploy: https://repo.maven.apache.org/maven2/com/heroku/sdk/heroku-maven-plugin/

**Comment by jkutner** [comment]
The release plugin ran, and created a tag/commit. But I don't see it in OSS either. Sometimes it takes a while to sync. If it's not up in an hour, I'll try again.

**Comment by jkutner** [comment]
@talbright it's up now http://repo1.maven.org/maven2/com/heroku/sdk/heroku-maven-plugin/1.2.0/

**Comment by talbright** [comment]
Works great, thanks!
