### ISSUE TITLE
Publish 1.0.2 to Maven Central

### ISSUE THREAD

**Issue by jamesward** [heroku/heroku-maven-plugin#28]
Looks like 1.0.1 and 1.0.2 haven't made it to Maven Central.

**Comment by jkutner** [comment]
Ack, forgot to sync bintray to maven central. should be up momentarily.

**Comment by jkutner** [comment]
It looks like something got messed up with 1.0.2, so I've released [1.0.3](http://repo1.maven.org/maven2/com/heroku/sdk/heroku-maven-plugin/1.0.3/) and updated the documentation accordingly. Thanks.
