### ISSUE TITLE
BASE64Encoder

### ISSUE THREAD

**Issue by DmitryKuchevsky** [heroku/heroku-maven-plugin#30]
Is it possible to change **sun.misc.BASE64Encode** to **java.util.Base64** ? Sun API is deprecated and as result maven produces the following error
`A required class was missing while executing com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy: sun/misc/BASE64Encoder`
Fix is easy. Just delete/comment line 10 in file **/heroku-maven-plugin/heroku-deploy/src/main/java/com/heroku/sdk/deploy/Deployer.java** and change line 316
to
`encodedApiKey = java.util.Base64.getEncoder().encodeToString((":" + apiKey).getBytes());`

**Comment by jkutner** [comment]
Good point! I'll get this fixed asap

**Comment by jkutner** [comment]
Oh, i think this will break Java 7 compatibility, which means I will need to start maintaining two branches of the code. That's ok, but it may take me a bit of time to get this fixed.
