### ISSUE TITLE
Build Output Reconnections

### ISSUE THREAD

**Issue by dmathieu** [heroku/heroku-maven-plugin#32]
We'd need to be able to handle disconnections from the build service.
Whenever the service disconnects before sending EOF, you should reconnect.

In order to only get the bytes you haven't received yet, you can specify a `Range` header with the following value: `Range: bytes=42`.
If you don't specify a range header, you will always get the full output. You could then skip the bytes already received locally.

Busl being moved to the platform means any connection can be killed with a 10 seconds notice when the app is deployed or the process is cycled, hence this requirement.

**Comment by Malax** [comment]
I think this has been fixed some time ago. I'll close this since this is an old issue.
