### ISSUE TITLE
Deploying nodejs app

### ISSUE THREAD

**Issue by flaviocordova** [heroku/heroku-maven-plugin#33]
I'm trying to use heroku-maven-plugin to deploy a nodejs app and I'm getting error when I try to set the buildpack to heroku/nodejs.

```
[INFO] -----> Deploying...
[INFO] remote: 
[INFO] remote:  !     error fetching custom buildpack
[INFO] remote: 
[INFO] remote:  !     Push failed
```

In the configuration section I added:

```
<buildpacks>
  <buildpack>heroku/nodejs</buildpack>
</buildpacks>
```

shouldn't it work ? I've tried to leave it unset and add the build back using the web admin pages but it doesn't seems to have any effect since node is not available on runtime.
The app includes a package.json file in the root to validate the buildpack.

**Comment by jkutner** [comment]
What version of `heroku-maven-plugin` are you using?

**Comment by jkutner** [comment]
Yea, I guess it doesn't support the shorthand (I expected it too). In any case, you can use:

```xml
<buildpacks>
  <buildpack>https://github.com/heroku/heroku-buildpack-nodejs</buildpack>
</buildpacks>
```

**Comment by jkutner** [comment]
Also be aware that if you want the Node.js buildpack to run against your `package.json` and JS files, you'll need to include them in the configuration with the `<includes>` element.

**Comment by flaviocordova** [comment]
Worked like a charm....
Thanks !
