### ISSUE TITLE
Stop server locally

### ISSUE THREAD

**Issue by gurkan0791** [heroku/heroku-maven-plugin#34]
I can execute my project locally using `mvn heroku:run-war` but I don't know how to stop server. I type control + C, server not stopped. 
Thanks.

**Comment by jkutner** [comment]
What platform are you using (Windows, Mac, Linux)? Also, what does happen when you hit Ctrl+C? Nothing at all?

**Comment by gurkan0791** [comment]
I'm using Windows 10. When I hit Ctrl+ C, I show "Terminate batch job(Y/N)?". Then, terminates mvn, stop server logs in the cmd but the server continues to run in the background ( 8080).
Thanks.

**Comment by Malax** [comment]
I'll close this since this is an old issue. Feel free to re-open if this is still relevant. Happy to help!
