### ISSUE TITLE
RunWarMojo doesn't split up JAVA_OPTS for ProcessBuilder

### ISSUE THREAD

**Issue by simons1911** [heroku/heroku-maven-plugin#38]
In RunWarMojo.execute(), fullCommand is a list that gets created with:

```java
List<String> fullCommand = new ArrayList<String>();
fullCommand.add(javaCommand);
if (null != javaOpts) fullCommand.add(javaOpts);
...
```

And later passed to `ProcessBuilder().command` with:

```java
ProcessBuilder pb = new ProcessBuilder().command(fullCommand.toArray(new String[fullCommand.size()]));
```

Shouldn't `javaOpts` be split so that each entry has a single JAVA_OPTS option and that no argument contains a space? 

With the existing code, I get bad error messages when I have multiple options on my JAVA_OPTS. Things would work if I have a single JAVA_OPTS. I'm on Linux. Thanks in advance!

**Comment by jkutner** [comment]
@simons1911 sorry for the delay on this. I've got a PR now, and will release soon.
