### ISSUE TITLE
Destination directory for included files

### ISSUE THREAD

**Issue by YuriGeinishAlgn** [heroku/heroku-maven-plugin#40]
Hi, would be good to have a way to map included files to their destination filesystem location. For example, there is src/heroku/Procfile, but it should be in /app/Procfile after deploy, not /app/src/heroku/Procfile.

Unless I'm missing something, the only option at the moment is to pollute the project directory with out of place files.

**Comment by jkutner** [comment]
@YuriGeinishAlgn I usually recommend creating a Maven module called `heroku` or `deployment` (a bit like you might have an `assembly` module to create a fat jar). You can put all the files you need at runtime in that module along with with heroku-maven-plugin configuration, and a dependency on your main JAR artifact. You can also use the Maven copy plugin if you need to copy certain files from other places. 

Then you run a command like `mvn heroku:deploy -pl heroku` or similar.

Let me know if you think this will work for you, or if you have any questions. I need to document this pattern, so if you're not familiar with the `assembly` pattern, I'll put together a full example for you (with docs).

**Comment by Malax** [comment]
I'll close this since this is an old issue with the last response coming from a maintainer. Feel free to re-open if this is still relevant. Happy to help!
