### ISSUE TITLE
deploy without rebuilding or copying dependencies 

### ISSUE THREAD

**Issue by szczebel** [heroku/heroku-maven-plugin#41]
I use Heroku only as deployment platform.
GitLab holds my code, GitLabCI builds and runs tests.

I'm using 'mvn heroku:deploy' as a last job in my build pipeline. My SpringBoot fatjar is already in /target. It doesn't need any dependencies. 

Expected behavior:
Plugin should just prepare a package to upload, going directly to this phase:
[INFO ]-----> Packaging application...

Actual behavior:
Plugin triggers compilation, test execution and copying dependencies to /target/dependency, and only then prepares a package to deploy. All those steps are not necessary, and only prolong build times.

Possible solution to stay backward-compatible:
Configuration option to switch off undesired stages:
<bypassPrePackageSteps>true</bypassPrePackageSteps>
(similar to <includeTarget>)

**Comment by jkutner** [comment]
The `heroku:deploy` command is bound to the `package` phase, and I'm unsure if Maven allows you to run it unbound from that phase. However, there is a common pattern for implementing this...

First, create a `deploy` module in your root `pom.xml`. In the `deploy` module, create `pom.xml` with the Heroku Maven Plugin configuration and nothing else (remove the plugin config from the root `pom.xml`).

Then, as part of the `deploy` module's package phase, copy your JAR file into the `deploy/target` directory. This should be picked up by the heroku maven plugin when it runs in this module.

I hope this helps. If you think there's a better approach, or a way we can change the code of the [DeployMojo](https://github.com/heroku/heroku-maven-plugin/blob/master/maven-plugin/src/main/java/com/heroku/sdk/maven/DeployMojo.java) I'm happy to do that as well.

**Comment by szczebel** [comment]
Hey,

Suggested workaround should do the trick, but I'm trying to propose a New Feature Request here, not just fix my minor problem with build time. And I'd like to believe that my use case is not that esoteric, so others might want to see it implemented as well, insetad of fallbacking to the workaround. 

So first, let me elaborate on my use case a bit:

- I have a SpringBoot app (so all dependencies are within the fatjar after mvn package; I don't want them copied to /target/dependencies - not needed for deployment)
- my heroku plugin has no [executions] declared, so doesn't get invoked by any maven phase. It does NOT execute when I run 'mvn install'
- my first CI job runs 'mvn install', so all my tests are run and the deployment artifact is generated in /target
- my second CI job, which runs only for master branch, calls 'mvn heroku:deploy'. I would expect that the plugin would just take the fatjar declared in [includes] section, which is already present in /target, and send it over to heroku for deployment (along with processType and other configured settings)
- instead, heroku:deploy does unnecessary work recompiling & rerunning tests, as well as unnecesarily copying dependencies

I'm not Mojo expert, but I believe this should be possible. E.g. Tomcat maven plugin works that way (executing mvn tomcat:redeploy does NOT rebuild anything).

On the copy dependencies issue, it is about DpeloyMojo.java line 32, which invokes CopyDependencies unconditionally. I'm proposing to add a flag to plugin configuration, so line 32 would become 'if(copyDependeciesRequired) CopyDependencies...'. SO I could set this flag to false in my config.

**Comment by jkutner** [comment]
Sure that makes sense. But I think i'll build this functionality into a new goal. Maybe `mvn heroku:deploy-only` or some other name (because people expect `heroku:deploy` to execute the package phase now).

**Comment by szczebel** [comment]
Ah, fully agree, separate goal makes perfect sense

**Comment by jkutner** [comment]
@szczebel any preference on the goal name?

**Comment by szczebel** [comment]
deploy-only sounds good to me

**Comment by jkutner** [comment]
This will be available in 2.0.5 (probably in the next hour or so)
