### ISSUE TITLE
Clarify license terms

### ISSUE THREAD

**Issue by AndreasKl** [heroku/heroku-maven-plugin#5]
Currently there is no hint about the license the plugin is released with. Please add a license.txt or if the code is not covered by a common oss-license a clear statement would be nice.

Btw. proper credits for https://github.com/TimMoore/mojo-executor are missing.

**Comment by jkutner** [comment]
Thanks for pointing this out -- really bad on my part. I've fixed the license with 0009fe317d0c15efa8520595eb84f566edfee509 and i'm going to merge #7 to resolve the mojo-executor part.
