### ISSUE TITLE
 A required class was missing while executing com.heroku.sdk:heroku-maven-plugin:2.0.16:deploy: org/apache/commons/io/filefilter/IOFileFilter

### ISSUE THREAD

**Issue by Jhozakova** [heroku/heroku-maven-plugin#58]
Hello,

I'm trying to deploy heroku app with mvn clean heroku:deploy
but getting error
[ERROR] Failed to execute goal com.heroku.sdk:heroku-maven-plugin:2.0.16:deploy (default-cli) on project clevertrip: Execution default-cli of goal com.heroku.sdk:heroku-maven-plugin:2.0.16:deploy
 failed: A required class was missing while executing com.heroku.sdk:heroku-maven-plugin:2.0.16:deploy: org/apache/commons/io/filefilter/IOFileFilter
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.heroku.sdk:heroku-maven-plugin:2.0.16
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/user/.m2/repository/com/heroku/sdk/heroku-maven-plugin/2.0.16/heroku-maven-plugin-2.0.16.jar
[ERROR] urls[1] = file:/C:/Users/user/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

I'm using maven 3.5.4 and jdk 11

Here is my herokuapp config

			<plugin>
				<groupId>com.heroku.sdk</groupId>
				<artifactId>heroku-maven-plugin</artifactId>
				<version>2.0.16</version>
				<configuration>
					<appName>myherokuappname</appName>
					<jdkVersion>11</jdkVersion>
					<processTypes>
						<web>java $JAVA_OPTS -Dserver.port=$PORT -cp target/classes:target/dependency/* com.mySpringBootClass</web>
						
					</processTypes>
				</configuration>
			</plugin>

**Comment by Malax** [comment]
Hello @Jhozakova!

Can you try version `3.0.1` and see if that resolves your problem?

**Comment by Malax** [comment]
I'm closing this as it looks stale. Feel free to re-open if your problem persists - I'm happy to help!
