### ISSUE TITLE
War vs. Standalone app

### ISSUE THREAD

**Issue by MartinLichtblau** [heroku/heroku-maven-plugin#6]
Could you clarify if it's possible to start a war file with a user defined command proccommand instead of the standard "java $JAVA_OPTS -jar target/dependency/webapp-runner.jar $WEBAPP_RUNNER_OPTS --port $PORT target/jhipherotravis-0.0.1-SNAPSHOT.war" command?

**Comment by jkutner** [comment]
Currently it is not possible (but it should be an easy addition as this was the original intention). I'll see if we can get this fixed in the next release.

**Comment by jkutner** [comment]
I should clarify, this is still possible by defining your own `Procfile` (or `<processType>`) and using the `heroku:deploy` goal instead of the `heroku:deploy-war` goal. But in this case, you would need to use the maven-dependency-plugin to include webapp-runner like this:

```xml
<build>
    ...
    <plugins>
        ...
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>2.3</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals><goal>copy</goal></goals>
                    <configuration>
                        <artifactItems>
                            <artifactItem>
                                <groupId>com.github.jsimone</groupId>
                                <artifactId>webapp-runner</artifactId>
                                <version>7.0.57.1</version>
                                <destFileName>webapp-runner.jar</destFileName>
                            </artifactItem>
                        </artifactItems>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by MartinLichtblau** [comment]
Ok, I didn't know that. I will try whether I can inject the Enviroment Variable to my Spring Modul like this. Thanks for the tip!

**Comment by jkutner** [comment]
If all you need to do is set an Environment Variable, you can do that with the regular `heroku:deploy-war` goal by adding some configuration to the plugin in your `pom.xml` like this:

```
<configVars>
  <MY_VAR>SomeValue</MY_VAR>
  <JAVA_OPTS>-Xss512k -XX:+UseCompressedOops</JAVA_OPTS>
</configVars>
```

Please let me know when you find something that works. I want to make sure we cover this case well.

**Comment by MartinLichtblau** [comment]
Ok, I think I already tried it like this. But after judging by the heroku logs it didn't include my vars this way. 
With the standalone "deploy" together with the following procfile it works. 
`web:    java -Xmx384m -Xss512k -XX:+UseCompressedOops -jar target/*.war --spring.profiles.active=prod --server.port=$PORT  --spring.datasource.heroku-url=$DATABASE_URL`
So if I use the deploy-war I have to include the the paramters as variable in the pom. I'm not sure whether I did the conversion correct:
```
<plugin>
				  <groupId>com.heroku.sdk</groupId>
				  <artifactId>heroku-maven-plugin</artifactId>
				  <version>0.3.0</version>
				  <configuration>
					<appName>jhiphero</appName>
					<spring.profiles.active>prod</spring.profiles.active>
					<server.port>$PORT</server.port>
					<spring.datasource.heroku-url>$DATABASE_URL<spring.datasource.heroku-url>
					<JAVA_OPTS>-Xmx384m -Xss512k -XX:+UseCompressedOops</JAVA_OPTS>
				  </configuration>
				</plugin>
```

**Comment by jkutner** [comment]
I think you will need it like this to use the `heroku:deploy-war` goal:

```xml
<plugin>
  <groupId>com.heroku.sdk</groupId>
  <artifactId>heroku-maven-plugin</artifactId>
  <version>0.3.0</version>
  <configuration>
    <appName>jhiphero</appName>
    <configVars>
      <JAVA_OPTS>--spring.profiles.active=prod --server.port=$PORT --spring.datasource.heroku-url=$DATABASE_URL -Xmx384m -Xss512k -XX:+UseCompressedOops</JAVA_OPTS>
    </configVars>
  </configuration>
</plugin>
```

**Comment by jkutner** [comment]
Ah no, I am wrong. The config vars do not support embedded config vars. So the `$PORT` and `$DATABASE_URL` will not be resolved.

**Comment by Malax** [comment]
I'll close this since this is an old issue with the last response coming from a maintainer. Feel free to re-open if this is still relevant. Happy to help!
