### ISSUE TITLE
Version 3.0.1 not working on Windows

### ISSUE THREAD

**Issue by davidpc-te** [heroku/heroku-maven-plugin#61]
Version 3.0.1 of the heroku-maven-plugin does not appear to work when deploying war files to Heroku from Windows. (Version 2.0.16 works fine.)

It appears that at least part of the problem is with the default command that is generated.
For version 2.0.16, I get:
`java $JAVA_OPTS -jar target/dependency/webapp-runner.jar $WEBAPP_RUNNER_OPTS --port $PORT target/example.war`
But for version 3.0.1, I get:
`java $JAVA_OPTS -jar webapp-runner.jar $WEBAPP_RUNNER_OPTS --port $PORT target\example.war
`

So the obvious problematic difference is that 3.0.1 is using a backslash in the WAR file path.

**Comment by Malax** [comment]
Thank you for your report and investigation! I'll get a fix ready as soon as possible.
