### ISSUE TITLE
Allow deployment of applications that use git-commit-id-plugin

### ISSUE THREAD

**Issue by ottlinger** [heroku/heroku-maven-plugin#81]
I'm totally new to Heroku and wanted to deploy my locally running SpringBoot2-app.

Unfortunately the current implementation seems to be running without any git information available during the build, resulting in build failures - I found a [gist](https://gist.github.com/tmullin/bd17e3a05607d2b11349ef73ebbca84d) trying to address this but I'm asking myself if the situation can be changed from within the maven plugin.

My application uses the plugin from within maven - pom.xml:

`

     <plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>4.0.3</version>
        <configuration>
          <excludeProperties>
            <excludeProperty>git.user.*</excludeProperty>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
            <failOnNoGitDirectory>false</failOnNoGitDirectory>
          </excludeProperties>
        </configuration>
      </plugin>
`
and injects a 

`
org.springframework.boot.info.GitProperties
`
bean into the application, which fails if I disable the plugin to allow deployment to Heroku.

Personally I wouldn't want to add a heroku-specific implementation to my application to just add versioning information ....
is there an easily available workaround for this situation? Can the .git-information somehow be injected into the build?

Thanks for any feedback

**Comment by Malax** [comment]
Hello @ottlinger, thanks for your feedback!

I think the main issue is not with the Heroku Maven plugin here. Your configuration has `generateGitPropertiesFile` and `generateGitPropertiesFile` inside the `excludeProperties` element.

I was able to get the plugin to work with the following configuration (based on their [using-the-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin.md) document):
```xml
<plugin>
    <groupId>pl.project13.maven</groupId>
    <artifactId>git-commit-id-plugin</artifactId>
    <version>4.0.3</version>
    <executions>
        <execution>
            <id>get-the-git-infos</id>
            <goals>
                <goal>revision</goal>
            </goals>
            <phase>initialize</phase>
        </execution>
    </executions>
    <configuration>
        <generateGitPropertiesFile>true</generateGitPropertiesFile>
        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
        <excludeProperties>
            <excludeProperty>git.user.*</excludeProperty>
        </excludeProperties>
        <commitIdGenerationMode>full</commitIdGenerationMode>
    </configuration>
</plugin>
```

Let me know if that helped you already. :) Happy to help!

**Comment by ottlinger** [comment]
@Malax thanks for your feedback  - after I adapted the plugin configuration the build itself does not fail, but the application does not come up as it's not able to properly wire in GitProperties.

`

2021-01-25T13:17:22.941276+00:00 app[web.1]: ***************************
2021-01-25T13:17:22.941277+00:00 app[web.1]: APPLICATION FAILED TO START
2021-01-25T13:17:22.941277+00:00 app[web.1]: ***************************
2021-01-25T13:17:22.941278+00:00 app[web.1]: 
2021-01-25T13:17:22.941278+00:00 app[web.1]: Description:
2021-01-25T13:17:22.941279+00:00 app[web.1]: 
2021-01-25T13:17:22.941280+00:00 app[web.1]: Parameter 1 of constructor in de.ivfy.registration.admin.VersionService required a bean of type 'org.springframework.boot.info.GitProperties' that could not be found.
2021-01-25T13:17:22.941280+00:00 app[web.1]: 
2021-01-25T13:17:22.941281+00:00 app[web.1]: 
2021-01-25T13:17:22.941281+00:00 app[web.1]: Action:
2021-01-25T13:17:22.941281+00:00 app[web.1]: 
2021-01-25T13:17:22.941282+00:00 app[web.1]: Consider defining a bean of type 'org.springframework.boot.info.GitProperties' in your configuration.

`

Running the app locally without the heroku wrapper works fine and the application context loads fully.

**Comment by ottlinger** [comment]
I'm not sure what's running differently during the heroku build, but I changed my application configuration to not have any configuration if built for Heroku:

`public VersionService(@Autowired(required = false) GitProperties gitProperties) {
`

This makes the app build and deploy properly, albeit without GitInformation.

**Comment by Malax** [comment]
Are you using the plugin in this repo to deploy your app? Just want to make sure we're on the same page here. 

My first guess would be that the file created by `git-commit-id-plugin` does not end up in the classpath of your application. It might not be created, created at an unexpected location or simply not part of the classpath (`-cp`).

What does your process in `Procfile` look like?

**Comment by ottlinger** [comment]
I deploy the app via Heroku CLI from its main branch. There are no heroku-specific profiles being used.

If I run the app locally it's just a mvn package running spring-boot's repackage.
The generated JAR contains a git.properties in BOOT-INF/classes.

I do not know what's going on when I do 
`git push heroku master
`
from my master branch.

All I see is that the generated app running on Heroku does not have a GitProperties bean.

**Comment by ottlinger** [comment]
@Malax I created a manual procfile that just starts the JAR (that contains the git.properties), but the GitProperties bean is not instantiated as well.

Procfile:
`web: java -jar target/myjar-1.0.0-SNAPSHOT.jar 
`

I do run
`heroku local
`with v7.47.11 linux-x64 node-v12.16.2

If I run the same version with
`mvn spring-boot:run
`everything works as expected

**Comment by ottlinger** [comment]
@Malax I just had a look at another build's log:

The problem is that - as the heroku build seems to run detached - the git-commit-plugin is unable to generate any build information and just skips its execution.

```
remote:        [INFO] --- git-commit-id-plugin:4.0.3:revision (default)
@ myApp ---
remote:        [INFO] dotGitDirectory is null, aborting execution!
```
Therefore above snippet tries to manually sneak in the relevant properties. Is there a way to somehow include the current .git into the heroku build?

**Comment by Malax** [comment]
Ah, I see. That's why I asked about your deployment method. This plugin in this repo here builds your app locally and not on Heroku itself. If you build locally, you have your `.git` directory and it should work. When building on Heroku, the `.git` directory it's not possible to access the `.git` directory.

Building locally and deploying with the plugin in this repository is the only workaround I can think of if you absolutely need the `.git` directory during build.

**Comment by ottlinger** [comment]
@Malax thanks for your feedback and proposals.

I didn't want to put heroku-specific stuff into my application.

When I played around I even realised that a locally added procfile mingles with the Deployment .... I wouldn't want to introduce any more special-cases into the application. At least I know it's not yet working properly.

The gist provided above is also a manual intervention that I hope to avoid.

Another possibility would be to inject the stuff as environment variables ..... but this seems to be out of scope for a heroku maven plugin I assume.

**Comment by Malax** [comment]
Hey @ottlinger, I'm sorry that the conversation in this issue died down, that's on me. ☹️ 

I will close this issue now because it's so old and not really related to this repository. If this is still a relevant issue to you, please open a support ticket so we can help you out. 

Again, I'm sorry this issue languished for so long. :(
