### ISSUE TITLE
JSON encoding does not encode newlines and results in hard to spot issues

### ISSUE THREAD

**Issue by AndreasKl** [heroku/heroku-maven-plugin#9]
In:

https://github.com/heroku/heroku-maven-plugin/blob/master/heroku-deploy/src/main/java/com/heroku/sdk/deploy/Slug.java#L88

only backslashes are encoded. If a pom file contains newlines in the runtime argument (e.g. due to line length limits in your auto-formatter) the upload of a slug will fail with a HTTP 422 error. 

As I'm not sure if it's OK to add an additional dependency I would just add http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeJson(java.lang.String) instead of rolling your own solution.

**Comment by jkutner** [comment]
Thanks for reporting!

**Comment by AndreasKl** [comment]
Thanks for fixing :+1:
